---
title: "Formatieve opdracht rna-seq daur2"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Importing map structure
library(fs)
library(here)

# Importing image files
library(png)
library(grid)
library(gridExtra)

```

```{r, echo=FALSE}

fs::dir_tree("~/documents/dsfb2/dsfb2_workflows_portfolio/dsfb2_workflows_portfolio/projecten/3a_formatieve_opdracht_rna-seq_daur2/rnaseq_ipsc")

```

```{r readme, echo=FALSE}

readme_3a_1 <-  rasterGrob(as.raster(readPNG("~/dsfb2/dsfb2_workflows_portfolio/dsfb2_workflows_portfolio/projecten/3a_formatieve_opdracht_rna-seq_daur2/readme_screenshot_3a_1.png")))
grid.arrange(readme_3a_1, ncol=1, top=textGrob("README from the RNA-seq formative assignment:", gp=gpar(fontsize=20,font=8)))

readme_3a_2 <-  rasterGrob(as.raster(readPNG("~/dsfb2/dsfb2_workflows_portfolio/dsfb2_workflows_portfolio/projecten/3a_formatieve_opdracht_rna-seq_daur2/readme_screenshot_3a_2.png")))
grid.arrange(readme_3a_2, ncol=1, top=textGrob("", gp=gpar(fontsize=20,font=8)))

```
